---

# Packer passes "--extra-vars packer_install_puppet=true"
- name: Run install puppet tasks
  include_tasks: puppet.yml
  when: packer_install_puppet is defined and (packer_install_puppet|bool)

- name: Configure Vagrant .ssh directory.
  file:
    path:  /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode:  0700

- name: Install Vagrant's public key.
  get_url:
    url:   https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest:  /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode:  0600

- name: Check if guest is VirtualBox
  stat: path=/home/vagrant/.vbox_version
  register: is_virtualbox

- include_tasks: virtualbox.yml
  when: is_virtualbox.stat.exists
