---
# Install Puppet 3 (for Debian 7 (Wheezy) and Debian 8 (Jessie))
#
# loosely modeled after
# https://github.ibm.com/clearleap-cp/clearplay_puppet/blob/master/aws_puppet_bootstrap.sh

# use wheezy repo even on Debian 8 (Jessie)
- set_fact:
    puppetlabs_repo_deb: 'puppetlabs-release-wheezy.deb'

# Wheezy Python 2.7.3 does not support SNI, so use curl
- name: Download puppet repo package
  command: "curl https://apt.puppetlabs.com/{{ puppetlabs_repo_deb }} -o /tmp/{{ puppetlabs_repo_deb }}"
  args:
    warn: no

- name: Install Puppet repo package
  apt:
    deb: "/tmp/{{ puppetlabs_repo_deb }}"

- name: Install Puppet agent
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - rsync
    - unzip
    - puppet=3.7.5-1puppetlabs1
    - puppet-common=3.7.5-1puppetlabs1
    - apt-transport-https
